version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: acai
    main: ./cmd/acai
    binary: acai
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=/tmp/zig-cc/x86_64-linux
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=/tmp/zig-cc/aarch64-linux
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: acai
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: felixgeelhaar
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    name: acai
    homepage: "https://github.com/felixgeelhaar/acai"
    description: "Go CLI and MCP server for Granola meeting intelligence"
    license: "MIT"
    install: |
      bin.install "acai"

release:
  github:
    owner: felixgeelhaar
    name: acai
  mode: replace
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
